<?php
$this->headTitle('Seite nicht gefunden');
?>
<div class="layoutSidebar contentImage">
    <figure class="noMobile"><img alt="<?php echo $this->translate('Entschuldigung'); ?>" src="/images/keyvisuals/15k2/error.jpg"></figure>
</div>
<div class="layoutContent contentImage">
    <h1><?php echo $this->translate('Entschuldigung'); ?></h1>
    <section class="continuousText contentCompany errorSite">
        <p><?php echo $this->translate('Diese Seite existiert leider nicht mehr.'); ?></p>
        <hr>
        <h2><?php echo $this->translate('Finden Sie den gewünschten Inhalt unter den folgenden Links'); ?>:</h2>
        <?php if(!empty($this->layout()->link)): ?>
            <?php
        $lastCategoryName = null;
        foreach($this->layout()->link as $item) {
            $sortOrder = intval($item['sortorder']);
            $currentCategory = $sortOrder - ($sortOrder % 1000);
            if ($currentCategory != $lastCategoryName) {
                if (!empty($lastCategoryName)) {
                   echo '</ul>';
                }
                echo '<ul><li><h3>' . $item['headline'] . '</h3></li>';
                $lastCategoryName = $currentCategory;
            }
            $url = $item['url'];
            if (is_null($url)) {
                $param = array_merge(
                    $item['parameter'],
                    array(
                        'controller'=>$item['controller'],
                        'action'=>$item['action'],
                        'language_code' => $this->layout()->language_code,
                        'country_code' => $this->layout()->country_code,
                    )
                );
                $url = $this->url(
                    'lang/trade/database',
                    $param
                );
            }
            echo '<li><a title="' . $item['label'] . '" href="' . $url . '" class="action">' . $item['label'] . '<i class="icon-angle-right-s"></i></a></li>';
        }
        if (!empty($lastCategoryName)) {
            echo '</ul>';
        }
        ?>
        <?php endif; ?>
        <section class="customerServiceInfoWrapper">
            <h2><?php echo $this->translate('Fehlermeldungen helfen uns dabei, casual-fashion.com besser zu machen.'); ?>
                    <br><?php echo $this->translate('Nehmen Sie gerne Kotakt mit uns auf, vielen Dank!'); ?></h2>
           <article class="_mail">
               <h3><?php echo $this->translate('E-Mail'); ?>: <a href="mailto:eshop@casual-fashion.com">eshop@casual-fashion.com</a></h3>
           </article>
           <article class="_phone">
               <h3><?php echo $this->translate('Phone'); ?>:<span class="phoneNumber"> +49 (0) 1803 &ndash; 678700<br> (<?php echo $this->translate('Mo-Fr'); ?> 08:30-18:00 <?php echo $this->translate('Uhr'); ?>)</span></h3>
               <p class="_subline"><?php echo $this->translate('9 Cent/Min. inkl. MwSt. aus dem Festnetz, max. 42 Cent/Min. inkl. MwSt. aus den Mobilfunknetzen, Tarife bei Anrufen aus dem Ausland können abweichen.'); ?></p>
               <p class="_subline"><?php echo $this->translate('Leider ist keine telefonische Bestellung möglich.'); ?></p>
           </article>
        </section>
    </section>
</div>

<?php if (preg_match('/^development/', APPLICATION_ENV) == 1): ?>
<div class="well">
	<h3>Weitere Informationen</h3>
	<table class="table">
		<?php if (isset($this->controller) && $this->controller): ?>
			<tr>
				<th>Controller</th>
				<td><?php echo $this->escapeHtml($this->controller) ?> <?php
					if (isset($this->controller_class)
						&& $this->controller_class
						&& $this->controller_class != $this->controller
					) {
						echo '(' . sprintf(('resolves to %s'), $this->escapeHtml($this->controller_class)) . ')';
					}
					?>
                </td>
			</tr>
		<?php endif ?>
		<?php if (isset($this->exception) && $this->exception): ?>
			<tr>
				<th>Exception</th>
				<td><?php echo get_class($this->exception); ?></td>
			</tr>
			<tr>
				<th>Datei</th>
				<td>
					<pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>
						:<?php echo $this->exception->getLine() ?></pre>
				</td>
			</tr>
			<tr>
				<th>Meldung</th>
				<td>
					<pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
				</td>
			</tr>
			<tr>
				<th>Stack&nbsp;Trace</th>
				<td>
					<pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
				</td>
			</tr>
		<?php endif ?>
	</table>
</div>
<?php endif; ?>
