<?php

namespace Application\Controller;

use Zend\Console\Request as ConsoleRequest;
use Zend\Filter\Word\CamelCaseToDash;
use Zend\Form\Element\Color;
use Zend\Mvc\Controller\AbstractActionController;
use ZFTool\Model\Skeleton;

class ConsoleController extends AbstractActionController
{
    /**
     * <Description, starting with capital letter>
     *
     * @return void
     */
    public function createAction()
    {
        $request = $this->getRequest();

        // Make sure that we are running in a console and the user has not tricked our
        // application into running this action from a public web server.
        if (!$request instanceof ConsoleRequest) {
            throw new \RuntimeException('You can only use this action from a console!');
        }
        $verbose = $request->getParam('verbose');


        $rootPath = realpath('.');
        $moduleRootPath = $rootPath . '/module';
        $configRootPath = $rootPath . '/config';
        $moduleNames = array(
            'Dashboard',
            'Orders',
            'Customers',
            'Products',
            'Collections',
            'GiftCards',
            'Reports',
            'Reports'
        );

        foreach ($moduleNames as $moduleName) {
            $console = $this->getServiceLocator()->get('console');

            $filter = new CamelCaseToDash();
            $viewDirectory = strtolower($filter->filter($moduleName));

            $moduleName = ucfirst($moduleName);
            mkdir("$moduleRootPath/$moduleName/config", 0777, true);
            mkdir("$moduleRootPath/$moduleName/src/$moduleName/Controller", 0777, true);
            mkdir("$moduleRootPath/$moduleName/view/$viewDirectory", 0777, true);

            // Create the Module.php
            file_put_contents("$moduleRootPath/$moduleName/Module.php", Skeleton::getModule($moduleName));

            // Create the module.config.php
            file_put_contents("$moduleRootPath/$moduleName/config/module.config.php", Skeleton::getModuleConfig($moduleName));

            // Add the module in application.config.php
            $application = require "$configRootPath/application.config.php";
            if (!in_array($moduleName, $application['modules'])) {
                $application['modules'][] = $moduleName;
                copy("$configRootPath/application.config.php", "$configRootPath/application.config.old");
                $content = <<<EOD
<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */

EOD;

                $content .= 'return ' . Skeleton::exportConfig($application) . ";\n";
                file_put_contents("$configRootPath/application.config.php", $content);
            }
            if ($rootPath === '.') {
                $console->writeLine("The module $moduleName has been created", Color::GREEN);
            } else {
                $console->writeLine("The module $moduleName has been created in $rootPath", Color::GREEN);
            }
        }


    }
}
