<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/space/index' => __DIR__ . '/view/application/space/index.phtml',
    'error/404'               => __DIR__ . '/view/error/404.phtml',
    'error/500'               => __DIR__ . '/view/error/500.phtml',
    'error/index'             => __DIR__ . '/view/error/index.phtml',
    'layout/layout'           => __DIR__ . '/view/layout/layout.phtml',
);
